import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/ueber-uns">Über Uns</Link>
          <Link href="/leistungen">Leistungen</Link>
          <Link href="/gewerbe">Gewerbe</Link>
          <Link href="/privat">Privat</Link>
          <Link href="/kontakt">Kontakt</Link>
          <Link href="/impressum">Impressum</Link>
          <Link href="/datenschutz">Datenschutz</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
